version: '3.8'

services:
  postgres:
    build: .
    container_name: custom_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: intecap52
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_net

networks:
  shared_net:
    external: true
    
volumes:
  postgres_data: